# name: Build Docker Image with ECS Fargate 
# on:
#   workflow_dispatch:    
    
      
# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       # 1. Code checkout
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       # 2. Docker setup
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       # 3. Login to DockerHub 
#       - name: Login to DockerHub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       # 4. Build & Push Docker image
#       - name: Build and Push Docker image
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           push: true
#           tags: krishnatejab17/project1:${{ github.sha }}
      
#commented out above code and added below code to push docker image to ECR instead of DockerHub