name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main
  workflow_dispatch:

# .github/workflows/deploy.yml (or equivalent)
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: project1-repo-development-ecr 
  ECS_SERVICE: project1-development-ecs-service  
  ECS_CLUSTER: project1-development-cluster      
  ECS_TASK_DEFINITION: project1-development-task-definition 
  CONTAINER_NAME: project1-development-container

jobs:
  deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest
    environment: production

    env:
      IMAGE_TAG: build-${{ github.run_number }}

    permissions:
      id-token: write     #must have for OIDC
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::828411126532:role/github-actions-oidc-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Tag Docker Image
        run: |
          echo "Building image with tag: ${{ env.IMAGE_TAG }}"
          docker build -t ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
          docker tag ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Push Docker Image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Debug Paths
        run: |
          echo "PWD:"
          pwd
          echo "Root directory contents:"
          ls -la
          echo "Terraform directory contents:"
          ls -la Terraform || echo "Terraform folder NOT found!"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: .
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: .
        run: terraform plan -input=false -out=tfplan -var-file="terraform.tfvars" -var="image_tag=${{ env.IMAGE_TAG }}"

      - name: Terraform Apply
        working-directory: .
        run: terraform apply -input=false -auto-approve tfplan

      - name : Force new deployment of ECS service
        run: |
          aws ecs update-service \
            --cluster ${{ env.ECS_CLUSTER }} \
            --service ${{ env.ECS_SERVICE }} \
            --force-new-deployment
      
      - name : Get Load Balancer DNS Name
        run: |
         aws elbv2 describe-load-balancers --names project1-development-alb --query 'LoadBalancers[0].DNSName' --output text

    