name: Scan with KICS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  kics-job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write   # Required for SARIF upload

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Run KICS Scan with SARIF result
        uses: checkmarx/kics-github-action@v1
        with:
          path: '.'
          output_path: 'results-dir'
          output_formats: 'sarif'
          fail_on: 'none'   # donâ€™t fail pipeline, still produce SARIF

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v4   # v4 is current
        with:
          sarif_file: results-dir/results.sarif

      - name: Upload SARIF artifact
        uses: actions/upload-artifact@v4             # v4 replaces v3
        with:
          name: kics-sarif
          path: results-dir/results.sarif